"""Rebuilds CREDITS.md and the credits the game itself shows.

    python3 tools/docs/build_credits.py

Every 3D model in this game came off Sketchfab under Creative Commons Attribution, where
crediting the author is a **licence condition**, not a courtesy. Keeping that list by hand
did not work: on 2026-09-20 an audit found fifteen models in the game and not in the file,
including the crowd, the umpire's chair and the truss over every court.

So the list is generated. The per-model `assets/sketchfab/*/ATTRIBUTION.md` files are
written by the `sketchfab` CLI at download time and are the source of truth for author,
licence and link. Whether a model is actually in the game is answered by grepping the
code for its path, so a model that stops being used says so instead of quietly claiming
a credit it no longer needs.

Two files come out:

  CREDITS.md            for the repository
  scripts/credits.gd    a GDScript constant, which is what the in-game screen reads

The game reads a script rather than a text file on purpose: a `.gd` is always in the
exported pack, and a loose `.txt` is only there if the export filters happen to include
it. A credits screen that is blank in the shipped build is worse than none.
"""

import os
import pathlib
import re
import textwrap

HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent.parent
MODELS = PROJECT / "assets" / "sketchfab"

# What each model is for, in the game's own words. The generator knows whether a model is
# used; only a person knows what it is.
USED_FOR = {
    "aggie_stadium_chair": "every seat in the stands",
    "badminton_racket_and_shuttlecock_low_poly": "the rackets and the shuttlecock",
    "beach_umbrella_low_poly": "the team umbrellas at the beach",
    "gym_bench_chair": "the team benches at the side of the court",
    "lifeguard_chair": "the umpire's high chair",
    "male_character_in_caual_clothing": "the officials, and the line judges",
    "metal_folding_chair": "the line judges' chairs and the officials' table",
    "olympic_athlete": "the players",
    "plastic_chair": "the players' and coaches' chairs at the side of the court",
    "rigging_truss_80cm_10meter_kolong": "the lighting truss over every indoor court",
    "simple_low_poly_character": "the crew, photographers and ball kids around the court",
    "sport_water_bottle": "the bottles at the side of the court",
    "sports_bag": "the bags at the side of the court",
    "stage_lights": "the lamps hanging under the truss",
    "tennis_racket": "the tennis rackets",
    "tv_camera": "the television cameras round every venue",
}

NOT_USED = "downloaded, not currently used in the game"

MADE_HERE = """\
## Made for this game

The four athletes, the spectator, their rig and every animation were built for this game
and are not from anywhere. They are generated by `tools/blender/character_forge.py`,
which can be re-run at any time:

    blender --background --python tools/blender/character_forge.py

The crowd is that same spectator, baked into static poses — sitting, leaning and on their
feet — by `tools/blender/crowd_poses.py`, because a MultiMesh has no skeleton and cannot
pose anybody.

The sepak takraw animations were keyed for this game by hand, as numbers, in
`tools/meshy/takraw_clips.py`.

The hall, the court, the nets and the umpire's chair are built in code.

## Interface type

Barlow Condensed and Barlow Semi Condensed, by The Barlow Project Authors (Jeremy Tribby).
<https://github.com/jpt/barlow> — SIL Open Font License 1.1, `assets/fonts/OFL.txt`.
"""


def used_models():
    """Which model folders the game's own code names, as opposed to its tests."""
    named = set()
    for root in ("scripts", "tools"):
        for path in (PROJECT / root).rglob("*"):
            if path.suffix not in (".gd", ".py"):
                continue
            for folder in re.findall(r"assets/sketchfab/([^/]+)/", path.read_text(errors="ignore")):
                named.add(folder)
    return named


def read_attribution(folder):
    path = MODELS / folder / "ATTRIBUTION.md"
    if not path.exists():
        return None
    text = path.read_text(errors="ignore")
    title = text.splitlines()[0].lstrip("# ").strip()
    fields = dict(re.findall(r"^- (Author|License|Source): (.+)$", text, re.M))
    return dict(
        title=title,
        author=fields.get("Author", "unknown").strip(),
        licence=fields.get("License", "unknown").strip(),
        source=fields.get("Source", "").strip(),
    )


def gather():
    used = used_models()
    entries = []
    for folder in sorted(os.listdir(MODELS)):
        if not (MODELS / folder).is_dir():
            continue
        found = read_attribution(folder)
        if found is None:
            continue
        found["folder"] = folder
        found["used_for"] = USED_FOR.get(folder, NOT_USED) if folder in used else NOT_USED
        found["in_game"] = folder in used
        entries.append(found)
    return entries


def markdown(entries):
    out = ["# Credits", "",
           "Every 3D model in this game came from Sketchfab under Creative Commons",
           "Attribution, which means crediting the author is a licence condition and not a",
           "courtesy.", "",
           "This file is generated by `tools/docs/build_credits.py` from the per-model",
           "`assets/sketchfab/*/ATTRIBUTION.md` files. Do not edit it by hand — a hand-kept",
           "list is how fifteen models ended up in the game and not in here.", "",
           "## Models in the game", ""]
    for entry in (e for e in entries if e["in_game"]):
        out += [f"### {entry['title']}",
                f"- Used for: {entry['used_for']}",
                f"- By: {entry['author']}",
                f"- {entry['source']}",
                f"- Licence: {entry['licence']}", ""]
    out += ["## Downloaded and not used", "",
            "Kept in the repository, credited anyway, and not in the shipped game.", ""]
    for entry in (e for e in entries if not e["in_game"]):
        out += [f"- **{entry['title']}** by {entry['author']} — {entry['licence']}", ""]
    out += [MADE_HERE]
    return "\n".join(out)


def for_the_game(entries):
    """The same credits as one string, wrapped for a screen rather than a file."""
    lines = ["REFEREE FOR FUN", "",
             "Every 3D model in this game comes from Sketchfab under Creative Commons",
             "Attribution. Crediting the author is a condition of that licence.", "",
             "MODELS", ""]
    for entry in (e for e in entries if e["in_game"]):
        lines.append(f"{entry['title']} — {entry['author']}")
        lines.append(f"    {entry['used_for']} · {entry['licence']}")
    lines += ["", "MADE FOR THIS GAME", "",
              "The four athletes, the spectator, their rig and every animation were",
              "generated by tools/blender/character_forge.py. The crowd is that same",
              "spectator baked into static poses. The sepak takraw animations were keyed",
              "by hand. The hall, the court, the nets and the umpire's chair are built",
              "in code.", "",
              "TYPE", "",
              "Barlow Condensed and Barlow Semi Condensed, by The Barlow Project",
              "Authors (Jeremy Tribby) — SIL Open Font License 1.1.", "",
              "AUDIO", "",
              "Every sound is CC0 or public domain. See assets/audio/SOURCES.md.", "",
              "Built with Godot 4.7."]
    return "\n".join(lines)


def main():
    entries = gather()
    (PROJECT / "CREDITS.md").write_text(markdown(entries))
    body = for_the_game(entries).replace("\\", "\\\\").replace('"', '\\"')
    script = textwrap.dedent('''\
        class_name Credits
        extends RefCounted

        ## The credits, as the game shows them.
        ##
        ## Generated by `tools/docs/build_credits.py` — do not edit by hand. It is a script
        ## rather than a text file because a `.gd` is always in the exported pack and a loose
        ## `.txt` is only there if the export filters happen to include it, and a credits
        ## screen that is blank in the shipped build is worse than no credits screen.

        const TEXT := """%s"""
        ''') % body
    (PROJECT / "scripts" / "credits.gd").write_text(script)
    shown = sum(1 for e in entries if e["in_game"])
    print(f"credited {shown} models in the game, {len(entries) - shown} downloaded and unused")
    print("  wrote CREDITS.md and scripts/credits.gd")


if __name__ == "__main__":
    main()
