class_name Credits
extends RefCounted

## The credits, as the game shows them.
##
## Generated by `tools/docs/build_credits.py` — do not edit by hand. It is a script
## rather than a text file because a `.gd` is always in the exported pack and a loose
## `.txt` is only there if the export filters happen to include it, and a credits
## screen that is blank in the shipped build is worse than no credits screen.

const TEXT := """REFEREE FOR FUN

Every 3D model in this game comes from Sketchfab under Creative Commons
Attribution. Crediting the author is a condition of that licence.

MODELS

Aggie Stadium Chair — joshua.mckimmey
    every seat in the stands · CC Attribution
Badminton Racket And Shuttlecock (Low Poly) — game_travel
    the rackets and the shuttlecock · CC Attribution
Beach Umbrella - Low Poly — Styro
    the team umbrellas at the beach · CC Attribution
Gym Bench Chair — MHKstudio
    the team benches at the side of the court · CC Attribution
Lifeguard Chair — Pixie3D
    the umpire's high chair · CC Attribution
Male Character In Caual Clothing — gamedevme
    the officials, and the line judges · CC Attribution
Metal Folding Chair — Chen CheHsuan
    the line judges' chairs and the officials' table · CC Attribution
Olympic athlete — StallionArtist
    the players · CC Attribution
Plastic Chair — Jazavac
    the players' and coaches' chairs at the side of the court · CC Attribution
RIGGING TRUSS 80CM 10METER KOLONG — eventdesignws
    the lighting truss over every indoor court · CC Attribution
Simple Low Poly Character — PIXELOKAY
    the crew, photographers and ball kids around the court · CC Attribution
Sport Water Bottle — rollthebryce
    the bottles at the side of the court · CC Attribution
Sports Bag — Zeps3D
    the bags at the side of the court · CC Attribution
STAGE LIGHTS ⭐ — Maxime GUINARD
    the lamps hanging under the truss · CC Attribution
Tennis racket — turtlemode
    the tennis rackets · CC Attribution
TV Camera — merlincodes
    the television cameras round every venue · CC Attribution

MADE FOR THIS GAME

The four athletes, the spectator, their rig and every animation were
generated by tools/blender/character_forge.py. The crowd is that same
spectator baked into static poses. The sepak takraw animations were keyed
by hand. The hall, the court, the nets and the umpire's chair are built
in code.

TYPE

Barlow Condensed and Barlow Semi Condensed, by The Barlow Project
Authors (Jeremy Tribby) — SIL Open Font License 1.1.

AUDIO

Every sound is CC0 or public domain. See assets/audio/SOURCES.md.

Built with Godot 4.7."""
