class_name Models
extends RefCounted

## Loads the downloaded Sketchfab models and makes them usable.
##
## Nothing that comes off an asset site arrives ready. Every model has its own idea
## of which way up it is, how big a metre is, and where its origin sits — one of
## these is two metres tall standing up, another is lying on its back with its origin
## in the middle of its chest. So everything goes through `_normalise`, which turns it
## the right way up, scales it to a real height and stands it on the floor at its own
## feet. After that the game can treat them all the same.
##
## If a model is missing — someone has cloned the repo without the assets, or a
## download failed — every one of these falls back to the boxes in `figure.gd`. A
## game that will not start because an athlete is missing is worse than a game with a
## box in it.

## The people in the game. Generated by Meshy, rigged by Meshy, and animated by
## tools/meshy/rig_clips.py — which puts the thirteen badminton clips onto Meshy's own
## skeleton, since Meshy's animation library has plenty of walks and dances in it and
## no idea what a smash is.
##
## There are two athletes and they are the same man in two kits, because that is what
## was asked for: one for the blue team and one for the red. Both players on a side are
## identical twins, which nobody minds, and the two sides are told apart by their kit
## rather than by a bib stuck on the front of them.
##
## They arrive at a real 1.80 m with their feet at the origin, so nothing here has to
## be scaled or stood up.
const PLAYERS := {
	Sides.Team.BLUE: "res://assets/meshy/player_blue/player_blue_animated.glb",
	Sides.Team.RED: "res://assets/meshy/player_red/player_red_animated.glb",
}

## The line judges: grey-haired, in a uniform shirt and trousers that are nobody's
## team colour, and carrying the seated clip they spend the whole match in.
const OFFICIAL_MODEL := "res://assets/meshy/official/official_animated.glb"

## The characters built in Blender by tools/blender/character_forge.py, kept as the
## fallback for a checkout without the Meshy assets in it.
const ATHLETES := [
	"res://assets/characters/athlete_tall.glb",
	"res://assets/characters/athlete_average.glb",
	"res://assets/characters/athlete_stocky.glb",
	"res://assets/characters/athlete_wiry.glb",
]
const SPECTATOR := "res://assets/characters/spectator.glb"

## Kept for the fallback path and for anyone comparing.
const ATHLETE := "res://assets/sketchfab/olympic_athlete/olympic_athlete.glb"
const OFFICIAL := "res://assets/sketchfab/male_character_in_caual_clothing/male_character_in_caual_clothing.glb"

## The bone a racket goes in. Every rig has its own name for it, so they are all tried.
const RACKET_HANDS := ["RightHand", "hand.R", "R.hand_028"]
const KIT := "res://assets/sketchfab/badminton_racket_and_shuttlecock_low_poly/badminton_racket_and_shuttlecock_low_poly.glb"

## The tennis racket, which is a different object rather than a bigger badminton one:
## the head is nearly twice as wide, the throat is a wedge rather than a shaft, and the
## whole thing is roughly the same length. A tennis player carrying a badminton racket
## reads as a mistake to anybody who has held either.
const TENNIS_KIT := "res://assets/sketchfab/tennis_racket/tennis_racket.glb"
const TENNIS_RACKET_NODE := "06-12-19_tennis_racket_export_v1_obj_cleaner_materialmerger_gles"

## Real heights, in metres.
const PLAYER_HEIGHT := 1.80
const OFFICIAL_HEIGHT := 1.76

## A badminton racket is about 67 cm long, and a shuttlecock about 8.5 cm. A tennis
## racket is 68.5 cm — near enough the same length, which is the surprise about them.
const RACKET_LENGTH := 0.67
const TENNIS_RACKET_LENGTH := 0.685

## A table tennis bat, which is a quarter the length of either racket. There is no
## downloaded model for one, so it is built here out of a disc and a handle — a bat is
## simple enough that a bought model would look no better and would need fitting.
const BAT_LENGTH := 0.26
const BAT_HEAD_RADIUS := 0.079
const BAT_BLADE_THICKNESS := 0.017

## How far the butt of the handle sits inside the fist rather than balanced on top of
## it. A hand closes around a grip; it does not hold a racket by the very end.
const GRIP_INSET := 0.05
const SHUTTLE_LENGTH := 0.085


## An athlete in their team's kit.
##
## The Meshy characters need no sizing at all — they are generated at a real height with
## their feet on the floor — so unlike the downloaded ones there is no settle() step.
## Put a racket in their hand and they are ready.
## `libero` picks the third character file — the same body in the repainted shirt. It is
## a model choice made before the figure is built rather than a material put on afterwards,
## because the material route does not draw (see `tools/meshy/bake_kit.py`).
## `clear` picks the high-contrast kit. Read from the settings by whoever builds the
## player, rather than reached for here, so this stays a lookup and the decision stays
## where the settings are known.
static func player(team: Sides.Team, libero := false, clear := false) -> Node3D:
	if clear and not libero:
		var plain := _load_ready(str(CLEAR_MODELS.get(team, "")))
		if plain != null:
			plain.set_meta("kitted", true)
			return plain
		push_warning("no clear kit for %s — falling back" % Sides.label(team))
	if libero:
		var kitted := _load_ready(str(LIBERO_MODELS.get(team, "")))
		if kitted != null:
			kitted.set_meta("kitted", true)
			return kitted
		push_warning("no libero model for %s — falling back to the team kit" % Sides.label(team))
	var figure := _load_ready(PLAYERS.get(team, PLAYERS[Sides.Team.BLUE]))
	if figure != null:
		# Their kit is already the right colour, so there is nothing to put on them.
		figure.set_meta("kitted", true)
		return figure

	# Without the Meshy assets, the characters forged in Blender, who wear one kit
	# between them and need a bib to say which side they are on.
	figure = _load_ready(ATHLETES[int(team) % ATHLETES.size()])
	if figure == null:
		figure = _load(ATHLETE, PLAYER_HEIGHT)
	if figure == null:
		return null
	figure.set_meta("bib_colour", Sides.colour(team))
	return figure


## A spectator, which is also what the line judges are dressed as. They come with a
## seated clip, so for the first time the line judges can actually sit down.
static func spectator() -> Node3D:
	return _load_ready(SPECTATOR)


## A character that arrives correct: right size, right way up, feet on the floor.
## Nothing to measure and nothing to correct.
static func _load_ready(path: String) -> Node3D:
	if not ResourceLoader.exists(path):
		return null
	var scene: PackedScene = load(path)
	if scene == null:
		return null
	var holder := Node3D.new()
	holder.name = path.get_file().get_basename()
	holder.add_child(scene.instantiate())
	holder.set_meta("model_scale", 1.0)
	holder.set_meta("forged", true)
	# Deliberately left on the court layer. This used to put everything it loaded on the
	# people layer, which was right for the racket and quietly disastrous for the
	# shuttlecock: the overhead camera draws the court layer only, so the one object it
	# exists to show was the one object culled out of it. The racket is moved to the
	# people layer by whoever puts it in a hand, which is where that decision belongs.
	return holder


## Puts the team bib on and a racket in the hand. Kept separate from `settle` and run
## strictly after it, because both of these are added to the holder rather than to the
## model, and so do not scale with it — measured while fitting, the bib sat at a fixed
## height and set a floor the fit could never get under. Every player came out about
## 1.4 m tall no matter what scale the model was given.
## `carries` names what goes in the hand: `&"badminton"`, `&"tennis"`, `&"bat"`, or
## `&""` for nothing at all.
## Beach and indoor volleyball players carry nothing, and a volleyball player holding a
## badminton racket is a funnier bug than it is a small one.
static func dress_player(figure: Node3D, carries := &"badminton") -> void:
	if figure == null:
		return
	# A bib, not a tint. Recolouring does not work: the kit is painted into the texture,
	# and red times blue is dark red, so both teams looked like one team. The Meshy
	# players do not need one — one of them is dressed in blue and the other in red.
	if not figure.get_meta("kitted", false):
		_add_bib(figure, figure.get_meta("bib_colour", Color.WHITE))
	_fit_sockets(figure)
	if carries != &"":
		_hold_racket(figure, carries)


## The bone a hand is, and the bone a kicking foot is. Every rig names them its own way,
## so they are all tried, the same as the racket hand.
const HITTING_HANDS := ["RightHand", "hand.R", "R.hand_028"]
const KICKING_FEET := ["RightFoot", "foot.R", "R.foot_028"]
const HEADERS := ["Head", "head", "head_02"]

## The other hand. Three of volleyball's four touches are made with both — a dig off the
## forearms, a set out of the fingers of both hands, a block with both arms over the tape —
## and the ball meets them in the middle, not at either one.
const OTHER_HANDS := ["LeftHand", "hand.L", "L.hand_028"]


## Hangs an empty on the hand, on the kicking foot and on the head, so that whoever is
## holding the figure can ask where any of them is at any moment.
##
## Volleyball and sepak takraw put nothing in the hand, so until now there was nothing on
## the rig to ask: a dig, a spike and a kick were all struck from the middle of the
## player's chest because that was the only point anybody knew. The racket has had this
## all along, by accident — it needs a bone attachment to be carried at all.
static func _fit_sockets(figure: Node3D) -> void:
	var skeleton := _find_skeleton(figure)
	if skeleton == null:
		return
	for pair in [["hand", HITTING_HANDS], ["foot", KICKING_FEET], ["head", HEADERS],
			["other_hand", OTHER_HANDS]]:
		var bone := ""
		for candidate in pair[1]:
			if skeleton.find_bone(candidate) >= 0:
				bone = candidate
				break
		if bone.is_empty():
			continue
		var socket := BoneAttachment3D.new()
		socket.name = "%sSocket" % String(pair[0]).capitalize()
		socket.bone_name = bone
		skeleton.add_child(socket)
		figure.set_meta(String(pair[0]), socket)


## Puts a racket in the player's right hand, on the bone, so it moves with the arm.
##
## The alternative — hanging it off the figure at a fixed offset — was fine while
## everybody stood still and looks ridiculous the moment their arms start swinging.
static func _hold_racket(figure: Node3D, carries := &"badminton") -> void:
	var held: Node3D = null
	var length := RACKET_LENGTH
	match carries:
		&"tennis":
			held = tennis_racket()
			length = TENNIS_RACKET_LENGTH
		&"bat":
			held = bat()
			length = BAT_LENGTH
		_:
			held = racket()
	if held == null:
		return
	# On the people layer with its owner, whichever way it ends up attached below. The
	# overhead camera leaves people out, and a racket that stayed on the court layer was
	# the one part of a player that turned up in the shuttle cam.
	_set_layer(held, Figure.PEOPLE_LAYER)

	var skeleton := _find_skeleton(figure)
	var hand := ""
	if skeleton != null:
		for candidate in RACKET_HANDS:
			if skeleton.find_bone(candidate) >= 0:
				hand = candidate
				break

	if hand.is_empty():
		# No hand to put it in, so it hangs at the side as it used to.
		held.position = Vector3(0.30, 0.74, 0.06)
		held.rotation = Vector3(deg_to_rad(-72.0), 0.0, deg_to_rad(-8.0))
		figure.add_child(held)
		figure.set_meta("racket", held)
		return

	var socket := BoneAttachment3D.new()
	socket.name = "RacketHand"
	socket.bone_name = hand
	skeleton.add_child(socket)
	socket.add_child(held)
	figure.set_meta("racket", held)

	# The skeleton lives inside a model that has been scaled to make the person a
	# real height, and anything parented to a bone inherits that. The racket was
	# already sized in metres, so the scaling has to be undone or it arrives either
	# enormous or invisible.
	# Which way a hand bone points is a decision each rig's author made separately, so
	# the racket is aimed per rig. On the Meshy skeleton the same quarter turn that
	# worked on the forged characters put the head of the racket below the fist and the
	# handle sticking up past the player's wrist.
	#
	# The offset along the racket's own length is the part that was wrong. `_part`
	# centres what it extracts on its own origin, so parenting the racket straight to a
	# hand bone balances it on the fist at its middle: the head hangs by the player's
	# thigh and the whole grip half is buried inside their leg. Measured on the model,
	# the head sits at the high end of its long axis and the grip at the low end, and
	# the quarter turn maps that axis onto the socket's Y — so shifting it half a
	# racket puts the butt of the handle in the hand and the head clear of the body.
	held.position = Vector3.ZERO
	held.rotation = Vector3(deg_to_rad(-90.0 if hand == "RightHand" else 90.0), 0.0, 0.0)

	# Anything parented to a bone inherits every scale between here and the model
	# root, and there is more than one. Rather than try to work out what they all
	# multiply to, the racket is measured where it has ended up and corrected.
	var box := _world_aabb(held)
	var longest := maxf(box.size.x, maxf(box.size.y, box.size.z))
	if longest > 0.0001:
		held.scale *= length / longest

	_slide_grip_into_hand(socket, held)


## Slides the racket along its own length until the butt of the handle is in the fist.
##
## `_part` centres what it extracts on its own origin, so a racket parented straight to a
## hand bone balances on the fist at its middle: the head hangs by the player's thigh and
## the grip half is buried in their leg.
##
## Everything here is measured in world space on purpose. A bone attachment inherits
## every scale between itself and the model root — on these characters that is a factor
## of about a hundred — so an offset written in the socket's own units does nothing
## visible at all, which is exactly what happened when this was a hardcoded number. The
## same trap the scale correction above already sidesteps.
##
## Which end is the head is measured too, rather than assumed. A racket is a wide flat
## oval on a thin rod, so the half of it with the larger spread away from its own axis is
## the head, and the other end is the one that belongs in the hand.
static func _slide_grip_into_hand(socket: Node3D, held: Node3D) -> void:
	var hand := socket.global_transform.origin
	var axis := socket.global_transform.basis.y.normalized()
	if axis.is_zero_approx():
		return

	var lowest := INF
	var highest := -INF
	var spread_low := 0.0
	var spread_high := 0.0
	var points: Array[float] = []
	var widths: Array[float] = []
	for node in _every(held):
		if not (node is MeshInstance3D) or (node as MeshInstance3D).mesh == null:
			continue
		var mesh: Mesh = (node as MeshInstance3D).mesh
		var place: Transform3D = (node as Node3D).global_transform
		for surface in mesh.get_surface_count():
			for v in mesh.surface_get_arrays(surface)[Mesh.ARRAY_VERTEX]:
				var offset: Vector3 = (place * v) - hand
				var along := offset.dot(axis)
				points.append(along)
				widths.append((offset - axis * along).length())
				lowest = minf(lowest, along)
				highest = maxf(highest, along)
	if points.is_empty() or highest <= lowest:
		return

	var middle := (lowest + highest) * 0.5
	for i in points.size():
		if points[i] < middle:
			spread_low = maxf(spread_low, widths[i])
		else:
			spread_high = maxf(spread_high, widths[i])

	# Move the grip end to just inside the fist, dragging the head out the other way.
	var grip := highest if spread_low > spread_high else lowest
	var along := -grip - GRIP_INSET * signf(grip)
	var shift := axis * along
	held.position += socket.global_transform.basis.inverse() * shift

	# And where the head finished, in the racket's own space, so that whoever is holding
	# it can find the part that touches the ball. It is measured here because this is the
	# one place that knows which end is which — the wide end is the head, and every number
	# above is in world space along the socket's own axis.
	var head := (lowest if grip == highest else highest) + along
	held.set_meta("head", held.global_transform.affine_inverse() * (hand + axis * head))


static func _world_aabb(node: Node3D) -> AABB:
	var box := AABB()
	var started := false
	for child in _every(node):
		if child is VisualInstance3D:
			var shape: AABB = (child as VisualInstance3D).get_aabb()
			if shape.size == Vector3.ZERO:
				continue
			var here: AABB = child.global_transform * shape
			box = here if not started else box.merge(here)
			started = true
	return box


## A band round the chest in the team's colour, bright enough to read across a hall.
## Puts a coloured bib on a character who already has a kit.
##
## Used for the libero, who has to be identifiable at a glance — that is the entire
## reason the different-shirt rule exists in the sport. A tint will not do it: the kit
## is painted into the texture, so multiplying it by yellow gives a dirty version of
## whatever it already was rather than a yellow shirt.
## Puts a whole figure, and everything hanging off it, on one visual layer.
static func set_layer(node: Node, layer: int) -> void:
	_set_layer(node, layer)


## The libero's kit: the same character in a different shirt, which is what the sport
## actually does.
##
## `wear_bib()` below strapped a 0.34 x 0.40 x 0.26 m box to the chest bone instead, and
## it read as exactly that. Luqman, 2026-09-17, on a screenshot of it: "change to
## different cloth, dont put block like that".
##
## The note above `wear_bib` was right that a material tint cannot do this — multiplying
## a red kit by yellow gives a dirty red, and stains the skin and shorts with it. What it
## missed is that the kit does not have to be tinted at runtime: it can be repainted once,
## in texture space, where the shirt is a separate region of the sheet. That is
## `tools/meshy/recolour_kit.py`, and it keeps every fold and seam because it moves the
## hue and leaves the relative light and shade alone.
##
## Falls back to the box if the repainted sheet is missing, the same way every model here
## falls back to a figure made of boxes: a libero in a bib is worse than a libero in a
## shirt and far better than a crash.
static func wear_libero_kit(figure: Node3D, sheet_path: String, fallback: Color) -> void:
	if figure == null:
		return
	if not ResourceLoader.exists(sheet_path):
		push_warning("no libero kit at %s — falling back to the bib" % sheet_path)
		wear_bib(figure, fallback)
		return
	var sheet: Texture2D = load(sheet_path)
	for node in figure.find_children("*", "MeshInstance3D", true, false):
		var mesh_instance := node as MeshInstance3D
		if mesh_instance.mesh == null:
			continue
		for surface in mesh_instance.mesh.get_surface_count():
			# `surface_get_material()` rather than `get_active_material()`. The latter is
			# what the first attempt used and it is the wrong question: on an imported
			# glTF the active material can come back from the ImporterMesh rather than
			# from the surface, and the copy made from it was never the material the
			# renderer was drawing — which is why the shirt stayed blue with a correct
			# yellow texture sitting on a correctly-found, visible mesh.
			var was: Material = mesh_instance.mesh.surface_get_material(surface)
			var now: StandardMaterial3D = (was.duplicate() if was is StandardMaterial3D
				else StandardMaterial3D.new())
			now.albedo_texture = sheet
			mesh_instance.set_surface_override_material(surface, now)
			# And a material_override as well, which outranks everything else on the
			# instance. Belt and braces on the one thing the player has to be able to see.
			mesh_instance.material_override = now


## The libero's own character file, wearing the repainted kit. A third model beside the
## two teams, not a material swapped onto one of them — see `tools/meshy/bake_kit.py`.
## The same two teams in kits that separate by brightness as well as hue, for players
## who turn on "Clearer team colours". A third and fourth character file rather than a
## tint, for the same reason the libero has its own: a material put onto a built figure
## does not draw.
const CLEAR_MODELS := {
	Sides.Team.RED: "res://assets/meshy/player_red_clear/player_red_clear_animated.glb",
	Sides.Team.BLUE: "res://assets/meshy/player_blue_clear/player_blue_clear_animated.glb",
}


const LIBERO_MODELS := {
	Sides.Team.RED: "res://assets/meshy/player_red_libero/player_red_libero_animated.glb",
	Sides.Team.BLUE: "res://assets/meshy/player_blue_libero/player_blue_libero_animated.glb",
}


static func wear_bib(figure: Node3D, colour: Color) -> void:
	if figure == null:
		return

	# On the chest bone, so it moves with the body.
	#
	# The plain bib below hangs off the model root, which is fine for a figure that
	# stands still and comes apart the moment one runs: the character leans into a
	# sprint and the bib stays bolt upright in the air behind them. The racket had the
	# same problem and the same answer.
	var skeleton := _find_skeleton(figure)
	var chest := ""
	if skeleton != null:
		for name in ["Spine02", "Spine01", "Spine", "Hips"]:
			if skeleton.find_bone(name) >= 0:
				chest = name
				break

	if chest.is_empty():
		_add_bib(figure, colour)
		return

	var socket := BoneAttachment3D.new()
	socket.name = "Bib"
	socket.bone_name = chest
	skeleton.add_child(socket)

	# A BoneAttachment3D inherits every scale between it and the model root, which on
	# these characters is about a hundred. So the vest is built at world size and then
	# divided by whatever it inherited, rather than guessed at in local units and found
	# to be either invisible or the size of the hall.
	var inherited := socket.global_transform.basis.get_scale()
	var factor := maxf(0.0001, inherited.x)

	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = 0.75

	var vest := MeshInstance3D.new()
	vest.name = "Vest"
	var mesh := BoxMesh.new()
	mesh.size = Vector3(0.34, 0.40, 0.26) / factor
	vest.mesh = mesh
	vest.position = Vector3(0.0, 0.06 / factor, 0.0)
	vest.material_override = material
	vest.layers = Figure.PEOPLE_LAYER
	socket.add_child(vest)


static func _add_bib(figure: Node3D, colour: Color) -> void:
	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = 0.75

	# Measured from the character rather than hardcoded, because the four athletes are
	# four different sizes and the bib has to sit on the chest of all of them. It also
	# has to be big: each athlete wears their own kit colour now, so the bib is the
	# only thing on court saying which side somebody is on.
	var box := _world_aabb(figure)
	var h: float = box.size.y if box.size.y > 0.2 else 1.80

	for band in [[h * 0.70, h * 0.085], [h * 0.585, h * 0.022]]:
		var mesh := BoxMesh.new()
		mesh.size = Vector3(h * 0.265, band[1], h * 0.205)
		var instance := MeshInstance3D.new()
		instance.name = "Bib"
		instance.mesh = mesh
		instance.position = Vector3(0.0, band[0], 0.0)
		instance.material_override = material
		instance.layers = Figure.PEOPLE_LAYER
		figure.add_child(instance)


## A line judge. Deliberately not in either team's colours.
## The AnimationPlayer inside a model, if it has one.
static func animator(figure: Node) -> AnimationPlayer:
	for child in _every(figure):
		if child is AnimationPlayer:
			return child
	return null


## Finds an animation whose name mentions any of `words`, because every model names
## its clips differently — one calls it "Run" and the next "Armature|walk2".
static func clip_named(player: AnimationPlayer, words: Array) -> String:
	if player == null:
		return ""
	for word in words:
		for name in player.get_animation_list():
			if String(name).to_lower().contains(String(word).to_lower()):
				return name
	return ""


## Makes a clip loop. Almost every downloaded animation arrives set to play once.
static func make_looping(player: AnimationPlayer, clip: String) -> void:
	if player == null or clip.is_empty() or not player.has_animation(clip):
		return
	var animation: Animation = player.get_animation(clip)
	animation.loop_mode = Animation.LOOP_LINEAR


## The skeleton inside a model, for anything that wants to pose it by hand.
static func skeleton_of(node: Node) -> Skeleton3D:
	return _find_skeleton(node)


## The upper arm bones, under whichever names this rig gave them.
##
## Every downloaded rig calls them something different, the same way every rig has its
## own word for a hand — see RACKET_HANDS. Returns the two bone indices, or -1 for one
## it could not find, so a caller can pose whichever arm it did get.
const ARM_BONES := {
	"right": ["RightArm", "upper_arm.R", "R.upperArm_026", "R.upperArm_04", "arm.R"],
	"left": ["LeftArm", "upper_arm.L", "L.upperArm_06", "L.upperArm_04", "arm.L"],
}


static func arms_of(skeleton: Skeleton3D) -> Dictionary:
	var found := {"right": -1, "left": -1}
	if skeleton == null:
		return found
	for side in ARM_BONES:
		for candidate in ARM_BONES[side]:
			var at := skeleton.find_bone(candidate)
			if at >= 0:
				found[side] = at
				break
	return found


## The rig inside a figure, for whoever needs to pose it and look at the result.
static func skeleton(figure: Node) -> Skeleton3D:
	return _find_skeleton(figure)


static func _find_skeleton(node: Node) -> Skeleton3D:
	for child in _every(node):
		if child is Skeleton3D:
			return child
	return null


## Sizes a model and stands it on the floor, then puts a racket in its hand if it is
## a player. This cannot happen when the model is built, which is the whole reason it
## is a separate call.
##
## A rigged character's mesh is skinned: its shape comes from the skeleton, and until
## the skeleton has entered the tree and posed itself, asking the mesh how big it is
## returns the raw bind-pose numbers in whatever units the artist happened to use.
## Sizing from those made every player about ten times too tall — the first thing
## visible on court was a pair of shoes the size of cars.
static func settle(figure: Node3D) -> void:
	if figure == null or figure.get_child_count() == 0:
		return
	# Rackets and shuttlecocks were sized when they were cut out of their pack and
	# have no business being resized to the height of a person. Neither do the forged
	# characters, which were built at the size they are meant to be.
	if not figure.has_meta("target_height"):
		return
	var model: Node3D = figure.get_child(0)
	var height: float = figure.get_meta("target_height", 1.80)

	var box := _in_tree_bounds(figure)

	# Stand it up if it arrived on its back. Exporters disagree about which axis is
	# up, and guessing per model was how the line judge ended up ten metres wide
	# earlier — so it is measured instead. A person is reliably taller than they are
	# deep, so a figure longer front-to-back than it is tall is lying down.
	if box.size.z > box.size.y * 1.4:
		model.rotation.x = deg_to_rad(-90.0)
		box = _in_tree_bounds(figure)

	if box.size.y > 0.001:
		var factor := height / box.size.y
		model.scale *= factor
		figure.set_meta("model_scale", model.scale.y)
		box = _in_tree_bounds(figure)

	# Feet on the floor, centred where the game thinks the person is standing.
	model.position -= Vector3(box.get_center().x, box.position.y, box.get_center().z)


## The size of everything under `figure`, measured in `figure`'s own space, with the
## skeleton posed. Only meaningful once the node is in the tree.
static func _in_tree_bounds(figure: Node3D) -> AABB:
	var into := figure.global_transform.affine_inverse()
	var box := AABB()
	var started := false
	for child in _every(figure):
		if not child is VisualInstance3D:
			continue
		# The mesh's own bind-pose bounds, not the engine's. VisualInstance3D.get_aabb()
		# on a skinned mesh is padded out to cover everywhere the animation might throw
		# a limb, which for a running character is most of a stride — measured from
		# that, a 1.8 m man came out 1.4 m tall and two and a third metres deep.
		var shape := AABB()
		if child is MeshInstance3D and (child as MeshInstance3D).mesh != null:
			shape = (child as MeshInstance3D).mesh.get_aabb()
		else:
			shape = (child as VisualInstance3D).get_aabb()
		if shape.size == Vector3.ZERO:
			continue

		# A skinned mesh is placed by its skeleton rather than by its own node.
		var placed_by: Node3D = child
		if child is MeshInstance3D:
			var driver: Node = child.get_node_or_null((child as MeshInstance3D).skeleton)
			if driver is Skeleton3D:
				placed_by = driver

		var here: AABB = (into * placed_by.global_transform) * shape
		box = here if not started else box.merge(here)
		started = true
	return box


## Whether this figure came from the forge, and so needs no sizing.
static func is_forged(figure: Node) -> bool:
	return figure != null and figure.has_meta("forged")


## A line judge: grey-haired, in a uniform shirt that is nobody's team colour, and
## carrying the seated clip they spend the whole of a real match in.
static func official() -> Node3D:
	var meshy := _load_ready(OFFICIAL_MODEL)
	if meshy != null:
		return meshy

	# The downloaded official, if the Meshy assets are not there. No correcting
	# rotation, despite the mesh inside this one measuring 1.83 x 0.31 x 1.80 and
	# looking exactly like a Z-up export lying on its back. That figure is the mesh's
	# *local* box, and Sketchfab's exporter has already put a quarter turn on the node
	# above it. Adding another one laid the poor man flat and made him ten metres wide.
	# Measure the assembled model, not the mesh inside it.
	return _load(OFFICIAL, OFFICIAL_HEIGHT)


static func racket() -> Node3D:
	return _part(KIT, "Obj_Racket", RACKET_LENGTH)


## The tennis racket. Its three meshes — frame, strings and grip — sit under one node
## whose name is the exporter's, so it is taken whole rather than a mesh at a time.
static func tennis_racket() -> Node3D:
	return _part(TENNIS_KIT, TENNIS_RACKET_NODE, TENNIS_RACKET_LENGTH)


## A table tennis bat, built rather than loaded: a red rubber face on a wooden blade,
## with a flared handle. Its long axis is Y with the head at the top, which is what
## `_hold_racket` expects of anything it puts in a hand.
static func bat() -> Node3D:
	var made := Node3D.new()
	made.name = "Bat"

	var blade := MeshInstance3D.new()
	blade.name = "Blade"
	var head := CylinderMesh.new()
	head.top_radius = BAT_HEAD_RADIUS
	head.bottom_radius = BAT_HEAD_RADIUS
	head.height = BAT_BLADE_THICKNESS
	head.radial_segments = 20
	blade.mesh = head
	# Lying in the plane of the swing, not flat like a drinks coaster.
	blade.rotation = Vector3(deg_to_rad(90.0), 0.0, 0.0)
	blade.position = Vector3(0.0, BAT_LENGTH * 0.5 - BAT_HEAD_RADIUS, 0.0)
	blade.material_override = _flat(Color(0.62, 0.09, 0.10))
	made.add_child(blade)

	var handle := MeshInstance3D.new()
	handle.name = "Handle"
	var grip := BoxMesh.new()
	grip.size = Vector3(0.028, BAT_LENGTH * 0.38, 0.019)
	handle.mesh = grip
	handle.position = Vector3(0.0, -BAT_LENGTH * 0.5 + BAT_LENGTH * 0.19, 0.0)
	handle.material_override = _flat(Color(0.42, 0.29, 0.17))
	made.add_child(handle)
	return made


static func _flat(colour: Color) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = 0.85
	return material


static func shuttlecock() -> Node3D:
	return _part(KIT, "Gp_Shuttle", SHUTTLE_LENGTH)


static func has_assets() -> bool:
	return ResourceLoader.exists(ATHLETE) and ResourceLoader.exists(KIT)


# --- making a downloaded model behave ------------------------------------------

## Instantiates a model, turns it upright, scales it to `height` and stands it on the
## floor with its feet at the origin.
## Instantiates a model and records the height it should end up. The sizing itself
## happens in settle(), once it is in the tree.
static func _load(path: String, height: float) -> Node3D:
	if not ResourceLoader.exists(path):
		return null
	var scene: PackedScene = load(path)
	if scene == null:
		return null

	var holder := Node3D.new()
	holder.name = path.get_file().get_basename()

	# holder -> pivot -> model. The pivot exists because the upright correction and
	# the scaling have to live on a node the animation cannot reach: these clips are
	# authored Z-up and animate the model root itself, so a rotation put there is
	# thrown away the moment anything starts playing and everybody lies down again.
	var pivot := Node3D.new()
	pivot.name = "Pivot"
	holder.add_child(pivot)

	var model: Node3D = scene.instantiate()
	pivot.add_child(model)
	holder.set_meta("target_height", height)
	holder.set_meta("model_scale", 1.0)
	# Deliberately left on the court layer. This used to put everything it loaded on the
	# people layer, which was right for the racket and quietly disastrous for the
	# shuttlecock: the overhead camera draws the court layer only, so the one object it
	# exists to show was the one object culled out of it. The racket is moved to the
	# people layer by whoever puts it in a hand, which is where that decision belongs.
	return holder


## Pulls one named piece out of a model — a racket out of a pack that also contains
## a shuttlecock and two spare rackets — and scales it on its longest side.
static func _part(path: String, part_name: String, length: float) -> Node3D:
	if not ResourceLoader.exists(path):
		return null
	var scene: PackedScene = load(path)
	if scene == null:
		return null

	var whole: Node3D = scene.instantiate()
	var found := _find(whole, part_name)
	if found == null:
		whole.queue_free()
		return null

	# Lift it out of the pack, and throw the rest away.
	var holder := Node3D.new()
	holder.name = part_name
	found.get_parent().remove_child(found)
	found.owner = null
	holder.add_child(found)
	whole.queue_free()

	var box := _bounds(found)
	var longest := maxf(box.size.x, maxf(box.size.y, box.size.z))
	if longest > 0.001:
		found.scale = Vector3.ONE * (length / longest)
		box = _bounds(found)
		found.position -= box.get_center()

	# Deliberately left on the court layer. This used to put everything it loaded on the
	# people layer, which was right for the racket and quietly disastrous for the
	# shuttlecock: the overhead camera draws the court layer only, so the one object it
	# exists to show was the one object culled out of it. The racket is moved to the
	# people layer by whoever puts it in a hand, which is where that decision belongs.
	return holder


## Multiplies every material by a colour, which tints a textured model without
## throwing the texture away — setting a material_override would lose it entirely.
static func _tint(node: Node, colour: Color) -> void:
	for child in _every(node):
		if not child is MeshInstance3D or child.mesh == null:
			continue
		for surface in child.mesh.get_surface_count():
			var material: Material = child.mesh.surface_get_material(surface)
			var tinted: StandardMaterial3D
			if material is StandardMaterial3D:
				tinted = material.duplicate()
			else:
				tinted = StandardMaterial3D.new()
			# Multiplying a dark kit by a dark colour gives black. The tint is
			# lightened so the team still reads at a glance, which matters more here
			# than the exact shade of somebody's shirt.
			tinted.albedo_color = colour.lerp(Color.WHITE, 0.30) * 1.35
			child.set_surface_override_material(surface, tinted)


## The size of everything under `node`, in `node`'s own space.
##
## Written as a descent that carries the transform down rather than a walk back up
## the parents, which is what the first version did and got wrong: a model given a
## quarter turn came back with its unrotated size, so it was scaled by the wrong
## dimension and ended up five times too big and still lying on its back.
static func _bounds(node: Node3D) -> AABB:
	var found := _gather(node, Transform3D.IDENTITY, AABB(), [false])
	return found


static func _gather(node: Node, so_far: Transform3D, box: AABB, started: Array) -> AABB:
	var here := so_far
	if node is Node3D:
		here = so_far * (node as Node3D).transform

	if node is MeshInstance3D and node.mesh != null:
		var piece: AABB = here * node.mesh.get_aabb()
		box = piece if not started[0] else box.merge(piece)
		started[0] = true

	for child in node.get_children():
		box = _gather(child, here, box, started)
	return box


static func _set_layer(node: Node, layer: int) -> void:
	for child in _every(node):
		if child is VisualInstance3D:
			child.layers = layer


static func _find(node: Node, wanted: String) -> Node3D:
	for child in _every(node):
		if child.name == wanted and child is Node3D:
			return child
	return null


static func _every(node: Node) -> Array:
	var found := [node]
	for child in node.get_children():
		found.append_array(_every(child))
	return found
